config/routes.rb
WirelessTechnologies::Application.routes.draw do
  resources :pages do 
    match 'antennas' , :on=>:member
    match 'antennas' , :on=>:collection
  end 
  root :to=>"pages#index"

end

app/models/page.rb
class Page < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  def antennas 
  end 

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Site</title>

  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="apple-mobile-web-app-capable" content="yes"> <!-- Display full-screen in standalone mode -->
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

  <link rel="apple-touch-icon" href="apple-touch-icon.png"/>
  <link rel="icon" href="favicon.ico"/>
  <!-- <link rel="author" href="humans.txt" /> -->

  <link rel="stylesheet" media="all" href="css/reset.css" />
  <link rel="stylesheet" media="all" href="css/main.css" />
  <link rel="stylesheet" media="all" href="css/utilities.css" />
  <link rel="stylesheet" media="screen" href="css/media.css" />
  <link rel="stylesheet" media="print" href="css/print.css" />
</head>
<body>
  <!-- Prompt IE 6/7/8 users to install Chrome Frame.
    Earlier IE doesn't have good enough Canvas support.
    Flash libraries that claim to add Canvas support back don't support some of
    the tricks we use like context.transform(). -->
  <!--[if lt IE 9 ]>
    <p class="chromeframe">
      You are using an <strong>outdated</strong> browser.
      <a href="http://browsehappy.com/">Upgrade to a different browser</a> or
      <a href="http://www.google.com/chromeframe/?redirect=true">install Google
        Chrome Frame</a> to experience this site.
    </p>
  <![endif]-->
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <title>WirelessTechnologies</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="js/libraries/stats.min.js"></script>
  <script src=")))js/combined.min.js"></script>
  <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
  <script src="js/app/main.js" charset="utf-8"></script>
  <div id="main">
    <div id="content">
      <noscript>You must have JavaScript enabled to use this site.</noscript>

      <div id="top-bar">
      </div>
        <h2>Algorithms to help with wireless technologies </h2>
        <ul>
          <li><%=link_to "Antennas" , antennas_pages_path %></li>  
        </ul>
 
      <div id="codez">
        <%=yield %>
      </div>  

    </div> <!-- /content -->
  </div> <!-- /main -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <!-- Google Analytics: change UA-XXXXXXXX-X to be your site's ID. -->
  <script>
  </script>
</body>
</html>

app/views/layouts/application_original.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WirelessTechnologies</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/antennas.html.erb
<h>Antennas</h3>

<div class="topic">
  <p>Calculate free space loss </p>
  Radiated power: Pt<%= text_field_tag "Pt" %>
</div>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% @pages.each do |page| %>
  <tr>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>